### ISSUE TITLE
Cannot pass an array to layer() inside a macro

### ISSUE THREAD

**Issue by msjyoo** [marcioAlmada/yay#19]
It is currently not possible, to my knowledge, to pass an array to the ·layer() parser inside a macro.

e.g. ·layer([',', ';']) results in "Expects ')' " parse error.

**Comment by marcioAlmada** [comment]
I think you can achieve this with `·brackets()` or `[ ·layer() ]`.

**Comment by sekjun9878** [comment]
@marcioAlmada I'm not sure that helps in this case. I think layer() is parsing balanced levels of the delimiter? In that case, I can't specify the delimiter for layer() to use inside a macro because trying to use array syntax inside a macro to pass the argument into layer() gives me an error.

**Comment by marcioAlmada** [comment]
Ok, I get you. This is because currently parsers inside macros only support a small subset of the PHP syntax: https://github.com/marcioAlmada/yay/blob/master/src/Macro.php#L384, only accepting:

* constants starting with `T_`
* literal strings 'foo' or ';'
* literal labels like `foo`, `if`, `list`
* a labeled token representation like `T_STRING·some_label` or `T_VARIABLE·my_var` (it's a first class shortcut for `·token(T_STRING)·label` or `·token(T_VARIABLE)·my_var`)
* other parsers with arguments following the rules above

There is no support for array arguments yet. The parser for macro parsers is declared here https://github.com/marcioAlmada/yay/blob/master/src/Macro.php#L148

Adding support for array "compilation"  is probably tricky.

**Comment by assertchris** [comment]
Should this be closed?

**Comment by marcioAlmada** [comment]
Finally fixing this through https://github.com/marcioAlmada/yay/commit/00a57eec4937c74f4f2f1b7a3d86a7c048b92dda :tada:

**Comment by msjyoo** [comment]
Wow a 3 year old issue being fixed, that’s super impressive!
